%% build_catss_requirements.m
% Builds the CATSS (Cislunar Autonomous Tended Station for cats) requirement
% baseline as two Requirements Toolbox sets:
%   1. CATSS_StakeholderNeeds.slreqx  - stakeholder needs (SN-xxx)
%   2. CATSS_SystemRequirements.slreqx - system requirements (SR-xxx)
% System requirements are linked to the stakeholder needs they derive from.
%
% Mission context: ~50 cats, cislunar (NRHO-class) orbit, 6-18 month resupply
% autonomy. Requirements are SOLUTION-NEUTRAL to preserve trade space for the
% architecture team. Bracketed [TBD]/[TBR] values are deliberate open trades.
%
% Author: generated for systems engineering handoff. R2025b.

slreq.clear;
outDir = "D:\dev\catsinspace\requirements";
if ~exist(outDir,'dir'); mkdir(outDir); end
oldDir = cd(outDir); cleanupObj = onCleanup(@() cd(oldDir)); %#ok<NASGU>

%% ------------------------------------------------------------------ %%
%% 1. STAKEHOLDER NEEDS
%% ------------------------------------------------------------------ %%
snFile = "CATSS_StakeholderNeeds";
if exist(snFile + ".slreqx",'file'); delete(snFile + ".slreqx"); end
snSet = slreq.new(char(snFile));
snSet.Description = ['CATSS Stakeholder Needs. Captures what stakeholders ' ...
    '(the cats, the sponsor, caretakers/operators, veterinary staff, and ' ...
    'safety/regulatory authorities) require of a ~50-cat cislunar station. ' ...
    'Solution-neutral. Source for the derived system requirements.'];
addAttribute(snSet,'Priority','Combobox','List',{'High','Medium','Low'}, ...
    'Description','Relative importance to mission success.');
addAttribute(snSet,'Stakeholder','Edit','Description','Primary stakeholder(s).');

% Sections: {key, summary}
snSections = {
    'SEC-SN-A','A. Feline Welfare & Behavior'
    'SEC-SN-B','B. Cost & Scalability'
    'SEC-SN-C','C. Mission & Autonomy'
    'SEC-SN-D','D. Safety & Compliance'
};
snSecMap = containers.Map;
for i = 1:size(snSections,1)
    c = add(snSet,'Id',snSections{i,1},'Summary',snSections{i,2},'Type','Container');
    snSecMap(snSections{i,1}) = c;
end

% Needs: {Id, Section, Priority, Stakeholder, Summary, Description, Rationale}
SN = {
'SN-001','SEC-SN-A','High','Cats', ...
 'Cats remain healthy and behave naturally', ...
 'The cats shall maintain physical health and the ability to express natural feline behaviors for the full mission duration.', ...
 'The colony is the reason the station exists; sustained physical and behavioral health is the top-level measure of mission success.';
'SN-002','SEC-SN-A','High','Cats', ...
 'Species-appropriate environment', ...
 'The environment supports feline territorial, climbing, scratching, and refuge behaviors in microgravity.', ...
 'Behavioral health depends on an environment that affords natural behaviors; deprivation causes chronic stress and welfare failure.';
'SN-003','SEC-SN-A','High','Cats; Veterinary', ...
 'Social structure managed', ...
 'The colony social structure is managed to minimize inter-cat stress, aggression, and resource competition.', ...
 'Cats are territorial and not obligately social; unmanaged grouping drives conflict, injury, and stress-related illness.';
'SN-004','SEC-SN-A','High','Cats; Veterinary', ...
 'Appropriate nutrition and hydration', ...
 'Nutrition and hydration are suited to feline physiology under microgravity conditions.', ...
 'Cats are obligate carnivores with specific dietary and low voluntary water intake; improper provision causes disease.';
'SN-005','SEC-SN-A','High','Cats; Operators', ...
 'Sanitation and waste management', ...
 'Sanitation and waste management keep cats clean and the habitat hygienic under microgravity.', ...
 'Elimination and grooming behavior plus hygiene are essential to health and to a habitable, odor-controlled cabin.';
'SN-006','SEC-SN-A','High','Veterinary; Operators', ...
 'Continuous health monitoring and care', ...
 'Feline health is continuously monitored and veterinary care is available throughout the mission.', ...
 'Early detection and treatment are the only mitigation for illness/injury given no rapid return-to-Earth in cislunar space.';
'SN-007','SEC-SN-A','Medium','Cats', ...
 'Circadian and sensory comfort', ...
 'A day/night lighting and sensory environment supports feline circadian rhythm and comfort.', ...
 'Disrupted circadian and sensory environments degrade sleep, behavior, and welfare over long-duration missions.';
'SN-008','SEC-SN-B','High','Sponsor', ...
 'Affordable to develop, launch, operate', ...
 'The station is affordable to develop, launch, and operate within the program budget.', ...
 'Affordability is a primary program driver and gates feasibility of the entire venture.';
'SN-009','SEC-SN-B','High','Sponsor; Operators', ...
 'Scalable through modular growth', ...
 'Colony capacity scales through modular growth without redesign of existing elements.', ...
 'Growth on orbit must not require redesign; modularity controls cost and risk of expansion.';
'SN-010','SEC-SN-B','High','Operators; Resupply provider', ...
 'Sustainable resupply logistics', ...
 'Resupply logistics are sustainable and cost-effective across the mission life.', ...
 'Recurring logistics dominate life-cycle cost for a long-duration crewed/occupied station.';
'SN-011','SEC-SN-B','High','Operators', ...
 'Low caretaking workload', ...
 'Day-to-day caretaking workload (human and/or robotic) is minimized to control recurring operating cost.', ...
 'Caretaker labor is a major recurring cost and crew-time constraint; automation directly reduces it.';
'SN-012','SEC-SN-C','High','Sponsor; Operators', ...
 'Cislunar autonomy between resupply', ...
 'The station operates in a cislunar orbit and sustains the colony autonomously between resupply visits.', ...
 'Cislunar distance makes frequent resupply and rapid intervention infeasible; the station must be self-sufficient for long intervals.';
'SN-013','SEC-SN-C','High','Cats; Safety authority', ...
 'Protection from space environment', ...
 'Occupants are protected from the cislunar radiation and thermal environment.', ...
 'Beyond the geomagnetic shield, radiation (GCR and solar particle events) and thermal extremes are life-limiting hazards.';
'SN-014','SEC-SN-D','High','Safety authority; Cats; Operators', ...
 'Protection from station hazards', ...
 'Occupants and caretakers are protected from credible station hazards including fire, depressurization, and loss of life support.', ...
 'These are the classic catastrophic spaceflight hazards; protection is mandatory for safety certification.';
'SN-015','SEC-SN-D','Medium','Safety/Regulatory authority', ...
 'Regulatory and welfare compliance', ...
 'The station complies with applicable human-spaceflight safety and animal-welfare standards, as tailored for this mission.', ...
 'Compliance is required for approval to launch and operate and codifies minimum acceptable welfare/safety practice.';
};

snMap = containers.Map;
for i = 1:size(SN,1)
    parent = snSecMap(SN{i,2});
    r = add(parent,'Id',SN{i,1},'Summary',SN{i,5}, ...
        'Description',SN{i,6},'Rationale',SN{i,7});
    setAttribute(r,'Priority',SN{i,3});
    setAttribute(r,'Stakeholder',SN{i,4});
    snMap(SN{i,1}) = r;
end
save(snSet);
fprintf('Stakeholder needs: %d needs in %d sections.\n', size(SN,1), size(snSections,1));

%% ------------------------------------------------------------------ %%
%% 2. SYSTEM REQUIREMENTS
%% ------------------------------------------------------------------ %%
srFile = "CATSS_SystemRequirements";
if exist(srFile + ".slreqx",'file'); delete(srFile + ".slreqx"); end
% Remove any stale link file so links are rebuilt cleanly against new sets
linkFiles = dir(char(srFile + "*.slmx"));
for li = 1:numel(linkFiles); delete(fullfile(linkFiles(li).folder, linkFiles(li).name)); end
srSet = slreq.new(char(srFile));
srSet.Description = ['CATSS System Requirements. Solution-neutral system-level ' ...
    'requirements derived from the CATSS Stakeholder Needs. Bracketed ' ...
    '[TBD]/[TBR] values mark open trades for the architecture team. Each ' ...
    'requirement carries a Derive link to its source stakeholder need(s).'];
addAttribute(srSet,'Priority','Combobox','List',{'High','Medium','Low'}, ...
    'Description','Relative importance to mission success.');
addAttribute(srSet,'VerificationMethod','Combobox', ...
    'List',{'Test','Analysis','Inspection','Demonstration'}, ...
    'Description','Primary intended verification method.');

srSections = {
    'SEC-1','1. Environmental Control & Life Support (ECLSS)'
    'SEC-2','2. Habitat & Feline Welfare'
    'SEC-3','3. Food, Water & Waste'
    'SEC-4','4. Health & Veterinary'
    'SEC-5','5. Operations & Autonomy'
    'SEC-6','6. Safety & Survivability'
    'SEC-7','7. Architecture, Cost & Interfaces'
    'SEC-8','8. Compliance'
};
srSecMap = containers.Map;
for i = 1:size(srSections,1)
    c = add(srSet,'Id',srSections{i,1},'Summary',srSections{i,2},'Type','Container');
    srSecMap(srSections{i,1}) = c;
end

% {Id, Section, Priority, VerifMethod, DerivesFrom(cellstr), Summary, Description, Rationale}
SR = {
% ---- ECLSS ----
'SR-001','SEC-1','High','Test',{'SN-014','SN-013'}, ...
 'Cabin total pressure', ...
 'The station shall maintain cabin total pressure of 101.3 kPa +/- 5% in occupied volumes.', ...
 'A stable sea-level-like pressure bounds physiological and hardware design and is a baseline habitability condition.';
'SR-002','SEC-1','High','Test',{'SN-001','SN-014'}, ...
 'Oxygen partial pressure', ...
 'The station shall maintain oxygen partial pressure between 19.5 and 23.1 kPa in occupied volumes.', ...
 'Maintains adequate oxygenation for cats while bounding flammability risk.';
'SR-003','SEC-1','High','Test',{'SN-001'}, ...
 'Carbon dioxide concentration', ...
 'The station shall maintain carbon dioxide partial pressure below 0.4 kPa (24-hour average) in occupied volumes.', ...
 'Elevated CO2 impairs health and behavior; cats are continuous CO2 producers requiring active scrubbing.';
'SR-004','SEC-1','High','Test',{'SN-007','SN-001'}, ...
 'Cabin temperature', ...
 'The station shall maintain cabin air temperature between 20 and 28 degC in occupied volumes [TBR].', ...
 'Cats tolerate a warmer comfort band than humans; range balances feline comfort against crew comfort and thermal cost.';
'SR-005','SEC-1','Medium','Test',{'SN-001'}, ...
 'Relative humidity', ...
 'The station shall maintain relative humidity between 30% and 70% in occupied volumes.', ...
 'Controls respiratory comfort, microbial growth, and static; bounds condensation in microgravity.';
'SR-006','SEC-1','High','Analysis',{'SN-010','SN-012'}, ...
 'Water recovery', ...
 'The station shall recover and recycle at least 90% of cabin water by mass [TBR].', ...
 'Water mass dominates resupply; high recovery is the primary lever for cislunar autonomy and logistics cost.';
'SR-007','SEC-1','High','Analysis',{'SN-001','SN-014'}, ...
 'CO2 removal capacity', ...
 'The station shall remove CO2 at the combined metabolic load of 50 cats plus up to [TBD] caretakers, with [TBD] margin.', ...
 'Scrubber sizing must envelope full occupancy plus caretaker presence with growth/contingency margin.';
'SR-008','SEC-1','Medium','Test',{'SN-002','SN-001'}, ...
 'Air particulate and dander control', ...
 'The station shall filter airborne particulates, including dander and litter dust, to within [TBD] air-quality limits.', ...
 'Dander/litter dust accumulate in microgravity, threatening feline and crew respiratory health and equipment.';
'SR-009','SEC-1','Medium','Demonstration',{'SN-002'}, ...
 'Odor control', ...
 'The station shall control cabin odor to within [TBD] limits.', ...
 'Odor is both a habitability and an early-indicator-of-fault concern in a closed cabin with many animals.';
% ---- Habitat & Feline Welfare ----
'SR-010','SEC-2','High','Analysis',{'SN-002'}, ...
 'Habitable volume per cat', ...
 'The station shall provide at least 1.5 m^3 of habitable volume per cat [TBR].', ...
 'Sets a quantitative welfare/sizing floor that scales the habitat trade space.';
'SR-011','SEC-2','High','Analysis',{'SN-002'}, ...
 'Three-dimensional territory', ...
 'The station shall provide at least 1.0 m^2 of perch and climbing surface per cat, distributed in three dimensions [TBR].', ...
 'Microgravity makes the full volume usable; vertical/3D territory is essential to feline behavior and conflict reduction.';
'SR-012','SEC-2','High','Demonstration',{'SN-002'}, ...
 'Claw-compatible grip surfaces', ...
 'The station shall provide claw-compatible textured surfaces for feline locomotion and stabilization throughout occupied volumes.', ...
 'Cats stabilize and translate using claws; without grippable surfaces they cannot locomote or self-stabilize in microgravity.';
'SR-013','SEC-2','Medium','Inspection',{'SN-002'}, ...
 'Scratching surfaces', ...
 'The station shall provide dedicated scratching surfaces, at least 1 per 6 cats [TBR].', ...
 'Scratching is a maintenance and marking behavior; deprivation harms welfare and redirects damage onto hardware.';
'SR-014','SEC-2','High','Inspection',{'SN-003','SN-002'}, ...
 'Refuge spaces', ...
 'The station shall provide enclosed refuge spaces, at least 1 per cat.', ...
 'Access to refuge is the primary feline coping mechanism for stress and conflict avoidance.';
'SR-015','SEC-2','High','Demonstration',{'SN-003'}, ...
 'Social-group partitioning', ...
 'The station shall provide reconfigurable partitioning to segregate the colony into social groups of no more than 12 cats [TBR].', ...
 'Smaller stable groups reduce aggression and disease spread and enable quarantine/management flexibility.';
'SR-016','SEC-2','Medium','Test',{'SN-007'}, ...
 'Circadian lighting', ...
 'The station shall provide programmable lighting with a 24-hour circadian cycle and adjustable photoperiod and intensity.', ...
 'A controlled light/dark cycle anchors feline circadian rhythm absent natural day/night in cislunar orbit.';
'SR-017','SEC-2','Medium','Test',{'SN-007','SN-003'}, ...
 'Acoustic noise limit', ...
 'The station shall limit sustained acoustic noise in occupied volumes to no more than 60 dBA [TBR].', ...
 'Cats hear and stress to higher frequencies/levels than humans; noise is a chronic stressor in machinery-dense habitats.';
'SR-018','SEC-2','Low','Demonstration',{'SN-002'}, ...
 'Behavioral enrichment', ...
 'The station shall provide behavioral enrichment (e.g., interactive, foraging, or play stimuli) in each habitat zone.', ...
 'Enrichment mitigates boredom-driven stress and abnormal behavior over long-duration confinement.';
% ---- Food, Water & Waste ----
'SR-019','SEC-3','High','Analysis',{'SN-004','SN-012'}, ...
 'Food storage and dispensing', ...
 'The station shall store and dispense food for 50 cats over the maximum resupply interval, plus 30% reserve.', ...
 'Food mass and shelf life size logistics and autonomy; reserve covers resupply slip and contingency.';
'SR-020','SEC-3','High','Analysis',{'SN-004','SN-012'}, ...
 'Potable water provision', ...
 'The station shall provide potable water for 50 cats at no less than 200 mL/cat/day, plus [TBD] reserve.', ...
 'Bounds hydration supply and recycling demand; cats have low voluntary intake so availability must be assured.';
'SR-021','SEC-3','Medium','Inspection',{'SN-004'}, ...
 'Feeding stations', ...
 'The station shall provide microgravity-compatible feeding stations, at least 1 per 8 cats [TBR].', ...
 'Adequate, distributed feeding access reduces resource-guarding conflict and ensures all cats feed.';
'SR-022','SEC-3','High','Test',{'SN-005','SN-014'}, ...
 'Waste capture and containment', ...
 'The station shall capture, contain, and process feline waste in microgravity with no uncontrolled release into the cabin.', ...
 'Free-floating waste is a hygiene, health, and equipment hazard unique to microgravity animal housing.';
'SR-023','SEC-3','Medium','Inspection',{'SN-005'}, ...
 'Elimination stations', ...
 'The station shall provide elimination stations, at least 1 per 4 cats [TBR].', ...
 'Sufficient, accessible elimination sites prevent inappropriate elimination and reduce stress/conflict.';
'SR-024','SEC-3','Medium','Analysis',{'SN-010','SN-012'}, ...
 'Resource recovery from waste', ...
 'The station shall recover usable resources (e.g., water) from feline waste where practical to support closed-loop autonomy [TBD targets].', ...
 'Closing loops on waste reduces resupply mass and extends autonomy, directly serving cost and mission drivers.';
% ---- Health & Veterinary ----
'SR-025','SEC-4','High','Demonstration',{'SN-006'}, ...
 'Individual health monitoring', ...
 'The station shall uniquely identify each cat and monitor individual health indicators: mass, activity, feeding, and body temperature.', ...
 'Per-individual monitoring enables early detection of illness in a large colony where group observation misses individuals.';
'SR-026','SEC-4','High','Inspection',{'SN-006'}, ...
 'Medical isolation capacity', ...
 'The station shall provide medical isolation capacity for at least 10% of the colony simultaneously [TBR].', ...
 'Isolation is required to contain infectious disease and to recover sick/injured cats away from the group.';
'SR-027','SEC-4','Medium','Demonstration',{'SN-006'}, ...
 'Veterinary work area', ...
 'The station shall provide a veterinary care area for examination and minor procedures.', ...
 'No rapid return-to-Earth exists in cislunar space; on-station veterinary capability is the only treatment path.';
% ---- Operations & Autonomy ----
'SR-028','SEC-5','High','Analysis',{'SN-012'}, ...
 'Autonomy duration', ...
 'The station shall sustain the colony without resupply for at least 12 months (threshold), 18 months (objective).', ...
 'Defines the autonomy interval that sizes consumables, recycling, and logistics; the central mission-profile requirement.';
'SR-029','SEC-5','High','Analysis',{'SN-012','SN-010'}, ...
 'Consumables margin', ...
 'The station shall retain at least 15% consumables margin at the end of each resupply interval [TBR].', ...
 'Margin protects against resupply slips and consumption uncertainty, preventing a welfare/safety cliff.';
'SR-030','SEC-5','High','Demonstration',{'SN-011'}, ...
 'Caretaking automation', ...
 'The station shall automate routine feeding, watering, and waste servicing such that caretaker attention does not exceed [TBD] caretaker-hours per day.', ...
 'Caretaker labor is a primary recurring cost; an explicit workload cap forces automation in the architecture trade.';
'SR-031','SEC-5','High','Test',{'SN-014'}, ...
 'Fault detection and annunciation', ...
 'The station shall autonomously detect, isolate, and annunciate faults in life-support-critical functions.', ...
 'Autonomous FDIR is required because cislunar latency/distance precludes timely ground intervention.';
'SR-032','SEC-5','Medium','Test',{'SN-012'}, ...
 'Earth communications', ...
 'The station shall support Earth communication tolerant of cislunar link availability and latency.', ...
 'Ground monitoring, vet tele-support, and operations all depend on a robust, latency-tolerant comm link.';
% ---- Safety & Survivability ----
'SR-033','SEC-6','High','Analysis',{'SN-014'}, ...
 'Fault tolerance', ...
 'The station shall be single-fault tolerant for any failure that could cause loss of the colony.', ...
 'One-fault tolerance for catastrophic outcomes is the baseline human-spaceflight safety posture, applied to the colony.';
'SR-034','SEC-6','High','Test',{'SN-014'}, ...
 'Fire detection and suppression', ...
 'The station shall detect and suppress fire in occupied and equipment volumes.', ...
 'Fire is a top catastrophic hazard in an oxygen-rich closed cabin; detection and suppression are mandatory.';
'SR-035','SEC-6','High','Analysis',{'SN-014'}, ...
 'Safe haven', ...
 'The station shall provide a safe-haven volume protecting all occupants for at least 24 hours during depressurization or contamination events [TBR].', ...
 'A protected refuge buys time for fault response or evacuation during the defining catastrophic events.';
'SR-036','SEC-6','High','Analysis',{'SN-013'}, ...
 'Radiation protection', ...
 'The station shall limit occupant radiation exposure to within [TBD] dose limits and provide sheltering against solar particle events.', ...
 'Cislunar radiation is a chronic and acute hazard; dose limits and SPE sheltering are required for long-duration occupancy.';
'SR-037','SEC-6','High','Test',{'SN-014'}, ...
 'Emergency power', ...
 'The station shall provide emergency power to life-support-critical loads for at least 24 hours after loss of primary power [TBR].', ...
 'Sustained critical-load power is required to survive a primary power failure long enough to recover or evacuate.';
% ---- Architecture, Cost & Interfaces ----
'SR-038','SEC-7','High','Analysis',{'SN-009'}, ...
 'Modular growth', ...
 'The station architecture shall allow habitat capacity to be added in increments of no more than 12 cats without redesigning existing modules.', ...
 'Bounded, redesign-free growth increments are the mechanism that makes scalability affordable and low-risk.';
'SR-039','SEC-7','High','Analysis',{'SN-008'}, ...
 'Launch envelope conformance', ...
 'Each launchable module shall fit within the mass and volume envelope of the reference launch-vehicle fairing ([TBD] kg, [TBD] m).', ...
 'Launch envelope is a hard architectural constraint and a primary cost driver per deployed module.';
'SR-040','SEC-7','High','Analysis',{'SN-008'}, ...
 'Design-to-cost', ...
 'The station shall meet design-to-cost targets of [TBD] for development and [TBD] recurring per module.', ...
 'An explicit cost target lets the team trade architectures against affordability rather than performance alone.';
'SR-041','SEC-7','Medium','Inspection',{'SN-009','SN-010'}, ...
 'Standardized interfaces', ...
 'The station shall use standardized berthing, docking, and resupply interfaces common across modules and resupply vehicles.', ...
 'Interface commonality enables modular growth and cheaper, interchangeable resupply.';
'SR-042','SEC-7','Medium','Analysis',{'SN-010'}, ...
 'Resupply cadence accommodation', ...
 'The station shall accommodate resupply visits no more frequent than the autonomy interval in SR-028.', ...
 'Logistics planning and interfaces must align with the autonomy interval to keep recurring cost sustainable.';
% ---- Compliance ----
'SR-043','SEC-8','Medium','Inspection',{'SN-015'}, ...
 'Human-spaceflight safety compliance', ...
 'The station shall comply with applicable human-spaceflight safety standards for crewed elements, as tailored for this mission [TBD standard set].', ...
 'Crewed elements must meet recognized safety standards to obtain approval to fly and operate.';
'SR-044','SEC-8','Medium','Inspection',{'SN-015'}, ...
 'Animal-welfare compliance', ...
 'The station shall comply with applicable animal-welfare standards for housing and care of the colony, as tailored for spaceflight [TBD standard set].', ...
 'Welfare compliance codifies minimum acceptable care and is required for ethical and regulatory approval.';
};

srMap = containers.Map;
nLinks = 0;
for i = 1:size(SR,1)
    parent = srSecMap(SR{i,2});
    r = add(parent,'Id',SR{i,1},'Summary',SR{i,6}, ...
        'Description',SR{i,7},'Rationale',SR{i,8});
    setAttribute(r,'Priority',SR{i,3});
    setAttribute(r,'VerificationMethod',SR{i,4});
    srMap(SR{i,1}) = r;
end
save(srSet);

% Derive links: SR -> SN
for i = 1:size(SR,1)
    src = srMap(SR{i,1});
    derivesFrom = SR{i,5};
    for k = 1:numel(derivesFrom)
        dst = snMap(derivesFrom{k});
        lk = slreq.createLink(src, dst);
        lk.Type = 'Derive';
        nLinks = nLinks + 1;
    end
end
save(srSet);

fprintf('System requirements: %d reqs in %d sections.\n', size(SR,1), size(srSections,1));
fprintf('Derive links created: %d.\n', nLinks);

%% ------------------------------------------------------------------ %%
%% 3. Coverage check: every stakeholder need has >=1 derived SR
%% ------------------------------------------------------------------ %%
covered = containers.Map(snMap.keys, num2cell(zeros(1,snMap.Count)));
for i = 1:size(SR,1)
    for k = 1:numel(SR{i,5})
        covered(SR{i,5}{k}) = covered(SR{i,5}{k}) + 1;
    end
end
uncovered = {};
ks = covered.keys;
for i = 1:numel(ks)
    if covered(ks{i}) == 0; uncovered{end+1} = ks{i}; end %#ok<SAGROW>
end
if isempty(uncovered)
    fprintf('Coverage check PASS: all %d stakeholder needs have >=1 derived system requirement.\n', snMap.Count);
else
    fprintf(2,'Coverage check FAIL: uncovered needs: %s\n', strjoin(uncovered,', '));
end

fprintf('\nArtifacts written to %s\n', outDir);
fprintf('  %s.slreqx\n  %s.slreqx\n', snFile, srFile);
slreq.clear;
